# Defines run jobs
#
# TIGER, FRASER, FT_EBEY are nested regions 
# and must be below PNW
#
# Template for CURR+N runs

# 00z
####################
0z-PNW+1
0z-PNW+2
0z-PNWRAT+1
0z-PNWRAT+2

# 06z
####################
6z-PNW+1
6z-PNW+2
6z-PNWRAT+1
6z-PNWRAT+2

# 12z
####################
12z-PNW+1
12z-PNW+2
12z-PNWRAT+1
12z-PNWRAT+2

# 18z
####################
18z-PNW+2
18z-PNW+3
18z-PNWRAT+1
18z-PNWRAT+2
