# Defines run jobs
#
# TIGER, FRASER, FT_EBEY are nested regions 
# and must be below PNW
#

# 00z
####################
0z-PNW
0z-PNW-WINDOW
0z-TIGER-WINDOW
0z-FRASER-WINDOW
0z-FT_EBEY-WINDOW
0z-PNWRAT

# 06z
####################
6z-PNW
6z-PNW-WINDOW
6z-TIGER-WINDOW
6z-FRASER-WINDOW
6z-PNWRAT

# 12z
####################
12z-PNW
12z-PNW-WINDOW
12z-TIGER-WINDOW
12z-FRASER-WINDOW
12z-PNWRAT

# 18z
####################
18z-PNW
18z-PNW-WINDOW
18z-TIGER-WINDOW
18z-FRASER-WINDOW
