&filetimespec
 START_YEAR = 2001
 START_MONTH = 07
 START_DAY = 09
 START_HOUR = 12
 START_MINUTE = 00
 START_SECOND = 00
 END_YEAR = 2001
 END_MONTH = 07
 END_DAY = 10
 END_HOUR = 12
 END_MINUTE = 00
 END_SECOND = 00
 INTERVAL = 10800
/
&gpinput_defs
 SRCNAME = 'ETA'
 SRCVTAB = 'ETA'
 SRCPATH = '[BASEDIR]/RASP/RUN/ETA/GRIB'
 SRCCYCLE = 1
 SRCDELAY = 3
/
